name: Publish Docker Image
on: [push]
jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
          name: utrecht-innovation/aries-cloudagent-webhook-receiver/aca-whr
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.pkg.github.com